CREATE TABLE Tabla_Canal OF Tipo_Canal 
(
	CONSTRAINT PK_Tabla_Canal PRIMARY KEY (Id)
)
NESTED TABLE Tiene_Video STORE AS Tabla_Lista_Video
	(NESTED TABLE Tiene_Comentario STORE AS Tabla_Lista_Comentario),
NESTED TABLE Seguidores STORE AS Tabla_Seguidores,
PCTFREE 70,
PCTUSED 30,
STORAGE( INITIAL 62644200 NEXT 62644200 PCTINCREASE 10);

CREATE TABLE Tabla_Usuario OF Tipo_Usuario
(
	CONSTRAINT PK_Tabla_Usuario PRIMARY KEY (Id)
)
NESTED TABLE Tiene_Canal STORE AS Tabla_Tiene_Canal,
NESTED TABLE Siguiendo STORE AS Tabla_Siguiendo,
PCTFREE 30,
PCTUSED 70,
STORAGE( INITIAL 90500 NEXT 90500 PCTINCREASE 10);
